server:
  port: 8091

eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:8403/eureka,http://127.0.0.1:8404/eureka
spring:
  application:
    name: zuul
  zipkin:  #指定zipkin server的地址
      base-url:  http://127.0.0.1:9001

#zuul把eureka拉取列表里所有服务给默认配置了 user-service: /user-service/**
zuul:
  ignored-services: '*' #忽略配置以下路由
  routes: #面向服务的路由规则配置
    user-service: /user/**  #简写：key是服务id，value是映射的路径  http://localhost:8091/user/user/zhangsan
    #原始写法
    #haha: #写什么无所谓
    #  path: /user-service/** #访问地址：http://localhost:8090/user-service/user/zhangsan
    #  serviceId: user-service #在rureka拉取服务列表(含有负载均衡) #url: http://127.0.0.1:8060
    #  strip-prefix: false 去除路由的前缀

#Zuul中默认就已经集成了Ribbon负载均衡和Hystix熔断机制
#但是所有的超时策略都是走的默认值，比如熔断超时时间只有1S,此建议手动配置

ribbon:
  ConnectTimeout: 500 # 连接超时时间(ms)
  ReadTimeout: 4000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000  # 熔断超时时长：6000ms

