server:
  port: 8061

#com.mysql.cj.jdbc.Driver驱动在url后面要加那一段
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: wangkf
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
          maximum-pool-size: 20
          minimum-idle: 10
  application:
    name: user-service
  zipkin:  #指定zipkin server的地址
    base-url:  http://127.0.0.1:9001

#mybatis扫描实体类对象包
mybatis:
  type-aliases-package: com.wangkf.pojo

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:8403/eureka,http://127.0.0.1:8404/eureka
  instance:
      prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
      ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找

